version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd!2023
      MYSQL_DATABASE: jwtTable
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:6.0
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

  spring-cloud-gateway:
    image: your-spring-cloud-gateway-image
    container_name: spring-cloud-gateway-container
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://mysql:3306/jwtTable
      - SPRING_R2DBC_USERNAME=root
      - SPRING_R2DBC_PASSWORD=P@ssw0rd!2023
      - SPRING_CLOUD_GATEWAY_ROUTES_0_ID=shortener-service
      - SPRING_CLOUD_GATEWAY_ROUTES_0_URI=http://localhost:8081
      - SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0_PATH=/shorten/**
      - SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0_StripPrefix=1
      - SPRING_CLOUD_GATEWAY_ROUTES_1_ID=redirect-service
      - SPRING_CLOUD_GATEWAY_ROUTES_1_URI=http://localhost:8082
      - SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0_PATH=/r/**
      - SPRING_CLOUD_GATEWAY_ROUTES_1_FILTERS_0_StripPrefix=1
      - SPRING_CLOUD_GATEWAY_DEFAULT_FILTERS_0_AddRequestHeader=X-Custom-Header,SomeValue
      - SPRING_CLOUD_GATEWAY_DEFAULT_FILTERS_1_AddRequestParameter=customParam,customValue
      - SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_1_name=RequestRateLimiter
      - SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_1_args_redis-rate-limiter.replenishRate=1
      - SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_1_args_redis-rate-limiter.burstCapacity=2
      - SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_1_args_key-resolver=#{@ipKeyResolver}
      - SPRING_DATASOURCE_URL=r2dbc:mysql://mysql:3306/jwtTable
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rd!2023
      - JWT_SECRET_KEY=my-secret-key
      - JWT_EXPIRATION=3600000
      - RATE_LIMIT_DEFAULT_TEXT="Too many requests. Please try again later."
      - RATE_LIMIT_MAX_REQUEST=10
      - RATE_LIMIT_TIME_WINDOW=60
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
