server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/jwtTable
    username: root
    password: P@ssw0rd!2023
  sql:
    init:
      mode: always

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Custom-Header, SomeValue
        - AddRequestParameter=customParam, customValue

      routes:
        - id: shortener-service
          uri: http://localhost:8081
          predicates:
            - Path=/shorten/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2
                key-resolver: "#{@ipKeyResolver}"

        - id: redirect-service
          uri: http://localhost:8082
          predicates:
            - Path=/r/**
          filters:
            - StripPrefix=1

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret-key: my-secret-key
  expiration: 3600000

rateLimitConfig:
  defaultText: "Too many requests. Please try again later."
  maxRequest: 10
  timeWindow: 60


