server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/url-shortener
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
